using UnityEngine;

public enum GUIStyles
{
    ToolbarButton,
    CNBox,
    Button,
    CNEntryBackEven,
    Toolbar,
    CNEntryInfo,
    CNEntryBackodd,
    CNStatusWarn,
    CNStatusError,
    Box,
    CNStatusInfo,
    CNCountBadge,
    MiniButtonMiddle,
    MiniButton,
    MiniButtonLeft,
    ErrorStyle,
    MiniButtonRight,
    LogStyle,
    CNMessage,
    WarningStyle,
    MessageStyle,
    EvenBackground,
    OddBackground,
    StatusError,
    ObjectPickerResultsGrid,
    PRLabel,
    ProjectBrowserGridLabel,
    ProjectBrowserHeaderBgMiddle,
    ProjectBrowserSubAssetExpandBtn,
    ToolbarDropDown,
    ToolbarSeachTextField,
    SearchCancelButtonEmpty,
    ToolbarSeachCancelButton,
    SearchTextField,
    ObjectPickerBackground,
    ObjectPickerPreviewBackground,
    Foldout,
    ProjectBrowserHeaderBgTop,
    NotificationBackground,
    ObjectPickerToolbar,
    PRPing,
    PRTextField,
    ProjectBrowserIconDropShadow,
    ProjectBrowserPreviewBg,
    CNEntryError,
    ProjectBrowserTextureIconDropShadow,
    ProjectBrowserSubAssetBg,
    ProjectBrowserSubAssetBgOpenEnded,
    WhiteLabel,
    CountBadge,
    StatusWarn,
    ProjectBrowserSubAssetBgDivider,
    InBigTitle,
    StatusLog,
    WhiteMiniLabel,
    LargeLabel,
    BoldLabel,
    ColorPickerBox,
    ProjectBrowserSubAssetBgCloseEnded,
    ProjectBrowserSubAssetBgMiddle,
    WordWrappedLabel,
    CNEntryWarn,
    MiniBoldLabel,
    MiniTextField,
    WhiteLargeLabel,
    WhiteBoldLabel,
    miniButton,
    miniButtonLeft,
    WordWrappedMiniLabel,
    miniButtonRight,
    Radio,
    ToolbarPopup,
    ToolbarTextField,
    MiniButtonMid,
    ToolbarSeachCancelButtonEmpty,
    ToolbarSeachTextFieldPopup,
    SearchCancelButton,
    HelpBox,
    AssetLabelPartial,
    MinMaxHorizontalSliderThumb,
    AssetLabelIcon,
    ProjectBrowserIconAreaBg,
    SelectionRect,
    AssetLabel,
    Label,
    DropDownButton,
    MiniLabel,
    FoldoutPreDrop,
    ProgressBarBack,
    ProgressBarBar,
    ProgressBarText,
    Tooltip,
    INTitle,
    miniBoldLabel,
    BoldToggle,
    TextField,
    INTitleText,
    NotificationText,
    ControlLabel,
    ToggleMixed,
    ObjectField,
    ObjectFieldThumb,
    MiniPopup,
    ObjectFieldMiniThumb,
    TextFieldDropDownText,
    Toggle,
    ColorField,
    TextFieldDropDown
}

public static class GUIStylesExtension_Create
{
    static readonly string[] names = new string[]
    {
        "ToolbarButton",
        "CN Box",
        "Button",
        "CN EntryBackEven",
        "Toolbar",
        "CN EntryInfo",
        "CN EntryBackodd",
        "CN StatusWarn",
        "CN StatusError",
        "Box",
        "CN StatusInfo",
        "CN CountBadge",
        "MiniButtonMiddle",
        "MiniButton",
        "MiniButtonLeft",
        "ErrorStyle",
        "MiniButtonRight",
        "LogStyle",
        "CN Message",
        "WarningStyle",
        "MessageStyle",
        "EvenBackground",
        "OddBackground",
        "StatusError",
        "ObjectPickerResultsGrid",
        "PR Label",
        "ProjectBrowserGridLabel",
        "ProjectBrowserHeaderBgMiddle",
        "ProjectBrowserSubAssetExpandBtn",
        "toolbarDropDown",
        "ToolbarSeachTextField",
        "SearchCancelButtonEmpty",
        "ToolbarSeachCancelButton",
        "SearchTextField",
        "ObjectPickerBackground",
        "ObjectPickerPreviewBackground",
        "Foldout",
        "ProjectBrowserHeaderBgTop",
        "NotificationBackground",
        "ObjectPickerToolbar",
        "PR Ping",
        "PR TextField",
        "ProjectBrowserIconDropShadow",
        "ProjectBrowserPreviewBg",
        "CN EntryError",
        "ProjectBrowserTextureIconDropShadow",
        "ProjectBrowserSubAssetBg",
        "ProjectBrowserSubAssetBgOpenEnded",
        "WhiteLabel",
        "CountBadge",
        "StatusWarn",
        "ProjectBrowserSubAssetBgDivider",
        "In BigTitle",
        "StatusLog",
        "WhiteMiniLabel",
        "LargeLabel",
        "BoldLabel",
        "ColorPickerBox",
        "ProjectBrowserSubAssetBgCloseEnded",
        "ProjectBrowserSubAssetBgMiddle",
        "WordWrappedLabel",
        "CN EntryWarn",
        "MiniBoldLabel",
        "MiniTextField",
        "WhiteLargeLabel",
        "WhiteBoldLabel",
        "miniButton",
        "miniButtonLeft",
        "WordWrappedMiniLabel",
        "miniButtonRight",
        "Radio",
        "toolbarPopup",
        "toolbarTextField",
        "miniButtonMid",
        "ToolbarSeachCancelButtonEmpty",
        "ToolbarSeachTextFieldPopup",
        "SearchCancelButton",
        "HelpBox",
        "AssetLabel Partial",
        "MinMaxHorizontalSliderThumb",
        "AssetLabel Icon",
        "ProjectBrowserIconAreaBg",
        "selectionRect",
        "AssetLabel",
        "Label",
        "DropDownButton",
        "MiniLabel",
        "FoldoutPreDrop",
        "ProgressBarBack",
        "ProgressBarBar",
        "ProgressBarText",
        "Tooltip",
        "IN Title",
        "MiniBoldLabel",
        "BoldToggle",
        "textField",
        "IN TitleText",
        "NotificationText",
        "ControlLabel",
        "ToggleMixed",
        "ObjectField",
        "ObjectFieldThumb",
        "MiniPopup",
        "ObjectFieldMiniThumb",
        "TextFieldDropDownText",
        "Toggle",
        "ColorField",
        "TextFieldDropDown"
    };

    public static GUIStyle Create(this GUIStyles style)
    {
        return new GUIStyle(names[(int)style]);
    }
}