#include "Assets/Utilities - AstrophelMoore/Essentials/Systems/UnityAddons/Resources/ComputeShaderGeneric.cginc"
#include "Assets/Utilities - AstrophelMoore/Essentials/Systems/UnityAddons/Resources/ComputableMeshGeneric.cginc"
#include "Assets/Utilities - AstrophelMoore/Essentials/Systems/UnityAddons/Resources/ComputableMesh_Edges.cginc"

#pragma kernel GetEdges

[numthreads(128, 1, 1)]
void GetEdges(uint id : SV_DispatchThreadID)
{
    if (id < indexCount)
    {
        int index = indexStart + (id * 3);
        edges[index].v1 = ExtractIndex(index);
        edges[index].v2 = ExtractIndex(index + 1);
        edges[index].index1 = index;
        edges[index].index2 = -1;
    
        edges[index + 1].v1 = ExtractIndex(index + 1);
        edges[index + 1].v2 = ExtractIndex(index + 2);
        edges[index + 1].index1 = index;
        edges[index + 1].index2 = -1;
    
        edges[index + 2].v1 = ExtractIndex(index + 2);
        edges[index + 2].v2 = ExtractIndex(index);
        edges[index + 2].index1 = index;
        edges[index + 2].index2 = -1;
    }
}

#pragma kernel ProccessDuplicateEdges

[numthreads(16, 16, 1)]
void ProccessDuplicateEdges(uint2 id : SV_DispatchThreadID)
{
    if ((id.y < indexCount) && (id.x < id.y))
        if (((edges[id.x].v1 == edges[id.y].v1) &&
            (edges[id.x].v2 == edges[id.y].v2))
            ||
            ((edges[id.x].v1 == edges[id.y].v2) &&
            (edges[id.x].v2 == edges[id.y].v1)))
        {
            uint idx = id.x + indexStart;
            uint idy = id.y + indexStart;
            // Duplicated edge triangle gets registered in the original edge
            edges[idx].index2 = edges[idy].index1;
            // Duplicated edge triangle's second value is marked as negative and
            // stores the codified value of original edge. Data is centralized in original edge.
            edges[idy].index2 = -int(idx) - 2;
        }
}
